services:
  jekyll:
    build: .
    image: arc42-site:latest
    init: true
    environment:
      JEKYLL_ENV: development
      POLLING: "--force_polling"
      JEKYLL_GITHUB_TOKEN: ${JEKYLL_GITHUB_TOKEN:-}
    volumes:
      - .:/site
      - jekyll_cache:/site/.jekyll-cache
      - sass_cache:/site/.sass-cache
    ports:
      - '4000:4000'
    command: >
      sh -c "bundle exec jekyll serve --host 0.0.0.0 --watch --incremental $${POLLING}"

volumes:
  jekyll_cache:
  sass_cache:
