# Writes _data/downloads.yml from manifest.json of the latest arc42-template release:
# languages (code, name, version, date) and formats (id, label) for the download page.
# Run through make: make sync-downloads (in the site's Docker image, Ruby standard library only).
# The generated file is committed, so the Netlify build never depends on GitHub.
#
# Order on the page: English first, then newest template version first, then by code;
# formats in FORMAT_ORDER, formats the page does not know yet at the end.
# Dates: the manifest's `date` is the template's own revdate, localised free text ("2026 年 9 月").
# When the manifest also carries `isoDate` (YYYY-MM, arc42-generator#88), `date` becomes
# "Sep 2026" for the English page and the localised text is kept as `date_local`.
require 'date'
require 'json'
require 'net/http'
require 'uri'
require 'yaml'

MANIFEST_URL = ENV.fetch('MANIFEST_URL',
  'https://github.com/arc42/arc42-template/releases/latest/download/manifest.json')
TARGET = File.expand_path('../_data/downloads.yml', __dir__)
FORMAT_ORDER = %w[asciidoc markdown docx pdf markdownMP gitHubMarkdown latex rst textile html
                  markdownStrict markdownMPStrict gitHubMarkdownMP docbook epub]

def fetch(url, redirects = 5)
  response = Net::HTTP.get_response(URI(url))
  case response
  when Net::HTTPRedirection
    abort "Too many redirects: #{url}" if redirects.zero?
    fetch(URI.join(url, response['location']).to_s, redirects - 1)
  when Net::HTTPSuccess then response.body
  else abort "✗ #{url}: HTTP #{response.code}"
  end
end

manifest = JSON.parse(fetch(MANIFEST_URL))
languages = manifest.fetch('languages')
formats = manifest.fetch('formats')
abort '✗ manifest.json lists no languages or formats' if languages.empty? || formats.empty?

def language_entry(lang)
  entry = lang.slice('code', 'name', 'version', 'date')
  iso = lang['isoDate'].to_s
  return entry unless iso.match?(/\A\d{4}-(0[1-9]|1[0-2])\z/)

  entry.merge('date' => Date.strptime(iso, '%Y-%m').strftime('%b %Y'), 'date_local' => lang['date'])
end

version_key = ->(v) { v.to_s.split('.').map(&:to_i) }
languages = languages.sort_by { |l| [l['code'] == 'EN' ? 0 : 1, version_key.(l['version']).map(&:-@), l['code']] }
formats = formats.sort_by { |f| [FORMAT_ORDER.index(f['id']) || FORMAT_ORDER.size, f['id']] }

data = {
  'release' => manifest['tag'],
  'template_commit' => manifest['templateCommit'],
  'languages' => languages.map { |l| language_entry(l) },
  'formats' => formats.map { |f| { 'id' => f['id'], 'label' => f['label'] } }
}
header = "# Generated by `make sync-downloads` from #{MANIFEST_URL}\n# Do not edit by hand.\n"
content = header + data.to_yaml(line_width: -1).sub(/\A---\n/, '')
old = File.exist?(TARGET) ? File.read(TARGET) : nil
# A broken or partial manifest must not shrink the download page unnoticed (e.g. in the
# scheduled workflow). Removing a language or format on purpose: ALLOW_FEWER=1.
if old && ENV['ALLOW_FEWER'] != '1'
  before = YAML.safe_load(old) || {}
  %w[languages formats].each do |key|
    had, has = before.fetch(key, []).size, data[key].size
    abort "✗ #{key}: #{has} in the release, #{had} on the page; set ALLOW_FEWER=1 if intended" if has < had
  end
end
if old == content
  puts "✓ #{File.basename(TARGET)} is up to date (release #{data['release']})"
else
  File.write(TARGET, content)
  puts "✓ Wrote #{File.basename(TARGET)}: release #{data['release']}, #{languages.size} languages, #{formats.size} formats"
end
